import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CountryResponse } from '../models/country.model';
import { StringMap } from '@angular/compiler/src/compiler_facade_interface';

@Injectable({
  providedIn: 'root'
})
export class CountryService {

  private countryName:string;
  //private countriesUrl = 'https://restcountries.eu/rest/v2/all';
  private countriesUrl = 'https://restcountries.com/v3.1/all';
  private countryUrl: string;
  private capitalUrl: string;
  private languageUrl: string;
  private continentUrl: string;



  constructor(private http: HttpClient) {
  }

  getCountries(){
  	return this.http.get<CountryResponse>(this.countriesUrl);
  }

  getCountry(countryName: string){
    //this.countryUrl =  `https://restcountries.eu/rest/v2/name/${ countryName }`;
    this.countryUrl =  `https://restcountries.com/v3.1/name/${ countryName }`;
    return this.http.get<CountryResponse>(this.countryUrl);
  }

  getCapital(capitalName: string){
    //this.capitalUrl = `https://restcountries.eu/rest/v2/capital/${ capitalName }`;
    this.capitalUrl = `https://restcountries.com/v3.1/capital/${ capitalName }`;
    return this.http.get<CountryResponse>(this.capitalUrl);
  }

  getLanguaje(languajeName: string){

    switch(languajeName){
      case "afar":  languajeName = "aa";
      break;
      case "abjasio":  languajeName = "ab";
      break;
      case "avéstico":  languajeName = "ae";
      break;
      case "afrikáans":  languajeName = "af";
      break;
      case "akano":  languajeName = "ak";
      break;
      case "amhárico":  languajeName = "am";
      break;
      case "aragonés":  languajeName = "an";
      break;
      case "árabe":  languajeName = "ar";
      break;
      case "arabe":  languajeName = "ar";
      break;
      case "asamés":  languajeName = "as";
      break;
      case "asames":  languajeName = "as";
      break;
      case "avar":  languajeName = "av";
      break;
      case "aimara":  languajeName = "ay";
      break;
      case "azerí":  languajeName = "az";
      break;
      case "baskir":  languajeName = "ba";
      break;
      case "bielorruso":  languajeName = "be";
      break;
      case "búlgaro":  languajeName = "bg";
      break;
      case "bhoyapurí":  languajeName = "bh";
      break;
      case "bislama":  languajeName = "bi";
      break;
      case "bambara":  languajeName = "bm";
      break;
      case "bengalí":  languajeName = "bn";
      break;
      case "tibetano":  languajeName = "bo";
      break;
      case "bretón":  languajeName = "br";
      break;
      case "breton":  languajeName = "br";
      break;
      case "bosnio":  languajeName = "bs";
      break;
      case "catalán":  languajeName = "ca";
      break;
      case "checheno":  languajeName = "ce";
      break;
      case "chamorro":  languajeName = "ch";
      break;
      case "corso":  languajeName = "co";
      break;
      case "cree":  languajeName = "cr";
      break;
      case "checo":  languajeName = "cs";
      break;
      case "eslavo eclesiástico antiguo":  languajeName = "cu";
      break;
      case "chuvasio":  languajeName = "cv";
      break;
      case "galés":  languajeName = "cy";
      break;
      case "danés":  languajeName = "da";
      break;
      case "alemán":  languajeName = "de";
      break;
      case "maldivo":  languajeName = "dv";
      break;
      case "dzongkha":  languajeName = "dz";
      break;
      case "ewé":  languajeName = "ee";
      break;
      case "griego":  languajeName = "el";
      break;
      case "inglés":  languajeName = "en";
      break;
      case "ingles":  languajeName = "en";
      break;
      case "esperanto":  languajeName = "eo";
      break;
      case "español":  languajeName = "es";
      break;
      case "estonio":  languajeName = "et";
      break;
      case "euskera":  languajeName = "eu";
      break;
      case "persa":  languajeName = "fa";
      break;
      case "fula":  languajeName = "ff";
      break;
      case "finés":  languajeName = "fi";
      break;
      case "fines":  languajeName = "fi";
      break;
      case "fiyiano":  languajeName = "fj";
      break;
      case "feroés":  languajeName = "fo";
      break;
      case "francés":  languajeName = "fr";
      break;
      case "frances":  languajeName = "fr";
      break;
      case "frisón":  languajeName = "fy";
      break;
      case "frison":  languajeName = "fy";
      break;
      case "irlandés":  languajeName = "ga";
      break;
      case "gaélico escocés":  languajeName = "gd";
      break;
      case "gallego":  languajeName = "gl";
      break;
      case "guaraní":  languajeName = "gn";
      break;
      case "guyaratí":  languajeName = "gu";
      break;
      case "guyarati":  languajeName = "gu";
      break;
      case "manés":  languajeName = "gv";
      break;
      case "manes":  languajeName = "gv";
      break;
      case "hausa":  languajeName = "ha";
      break;
      case "hebreo":  languajeName = "he";
      break;
      case "hindi":  languajeName = "hi";
      break;
      case "hiri motu":  languajeName = "ho";
      break;
      case "croata":  languajeName = "hr";
      break;
      case "haitiano":  languajeName = "ht";
      break;
      case "húngaro":  languajeName = "hu";
      break;
      case "armenio":  languajeName = "hy";
      break;
      case "herero":  languajeName = "hz";
      break;
      case "interlingua":  languajeName = "ia";
      break;
      case "indonesio":  languajeName = "id";
      break;
      case "occidental":  languajeName = "ie";
      break;
      case "igbo":  languajeName = "ig";
      break;
      case "yi de Sichuán":  languajeName = "ii";
      break;
      case "iñupiaq":  languajeName = "ik";
      break;
      case "ido":  languajeName = "io";
      break;
      case "islandés":  languajeName = "is";
      break;
      case "islandes":  languajeName = "is";
      break;
      case "italiano":  languajeName = "it";
      break;
      case "inuktitut":  languajeName = "iu";
      break;
      case "japonés":  languajeName = "ja";
      break;
      case "japones":  languajeName = "ja";
      break;
      case "javanés":  languajeName = "jv";
      break;
      case "javanes":  languajeName = "jv";
      break;
      case "georgiano":  languajeName = "ka";
      break;
      case "kongo":  languajeName = "ko";
      break;
      case "kikuyu":  languajeName = "ki";
      break;
      case "kuanyama":  languajeName = "kj";
      break;
      case "kazajo":  languajeName = "kk";
      break;
      case "groenlandés":  languajeName = "kl";
      break;
      case "groenlandes":  languajeName = "kl";
      break;
      case "camboyano":  languajeName = "km";
      break;
      case "canarés":  languajeName = "kn";
      break;
      case "canares":  languajeName = "kn";
      break;
      case "coreano":  languajeName = "ko";
      break;
      case "kanuri":  languajeName = "kr";
      break;
      case "cachemiro":  languajeName = "ks";
      break;
      case "kurdo":  languajeName = "ku";
      break;
      case "komi":  languajeName = "kv";
      break;
      case "córnico":  languajeName = "kw";
      break;
      case "cornico":  languajeName = "kw";
      break;
      case "kirguís":  languajeName = "ky";
      break;
      case "kirguis":  languajeName = "ky";
      break;
      case "latín":  languajeName = "la";
      break;
      case "latin":  languajeName = "la";
      break;
      case "luxemburgués":  languajeName = "lv";
      break;
      case "luganda":  languajeName = "lg";
      break;
      case "limburgués":  languajeName = "li";
      break;
      case "limburgues":  languajeName = "li";
      break;
      case "lingala":  languajeName = "ln";
      break;
      case "lao":  languajeName = "lo";
      break;
      case "lituano":  languajeName = "lt";
      break;
      case "luba-katanga":  languajeName = "lu";
      break;
      case "letón":  languajeName = "lv";
      break;
      case "leton":  languajeName = "lv";
      break;
      case "malgache":  languajeName = "mg";
      break;
      case "marshalés":  languajeName = "mh";
      break;
      case "marshales":  languajeName = "mh";
      break;
      case "maorí":  languajeName = "mi";
      break;
      case "maori":  languajeName = "mi";
      break;
      case "macedonio":  languajeName = "mk";
      break;
      case "malayalam":  languajeName = "ml";
      break;
      case "mongol":  languajeName = "mn";
      break;
      case "maratí":  languajeName = "mr";
      break;
      case "marati":  languajeName = "mr";
      break;
      case "malayo":  languajeName = "ms";
      break;
      case "maltés":  languajeName = "mt";
      break;
      case "maltes":  languajeName = "mt";
      break;
      case "birmano":  languajeName = "my";
      break;
      case "nauruano":  languajeName = "na";
      break;
      case "noruego bokmål":  languajeName = "nb";
      break;
      case "ndebele del norte":  languajeName = "nd";
      break;
      case "nepalí":  languajeName = "ne";
      break;
      case "nepali":  languajeName = "ne";
      break;
      case "ndonga":  languajeName = "ng";
      break;
      case "neerlandés":  languajeName = "nl";
      break;
      case "nynorsk":  languajeName = "nn";
      break;
      case "noruego":  languajeName = "no";
      break;
      case "ndebele del sur":  languajeName = "nr";
      break;
      case "navajo":  languajeName = "nv";
      break;
      case "chichewa":  languajeName = "ny";
      break;
      case "occitano":  languajeName = "oc";
      break;
      case "ojibwa":  languajeName = "oj";
      break;
      case "oromo":  languajeName = "om";
      break;
      case "oriya":  languajeName = "or";
      break;
      case "osético":  languajeName = "os";
      break;
      case "osetico":  languajeName = "os";
      break;
      case "panyabí":  languajeName = "pa";
      break;
      case "panyabi":  languajeName = "pa";
      break;
      case "pali":  languajeName = "pi";
      break;
      case "polaco":  languajeName = "pl";
      break;
      case "pastú":  languajeName = "ps";
      break;
      case "pastu":  languajeName = "ps";
      break;
      case "portugués":  languajeName = "pt";
      break;
      case "portugues":  languajeName = "pt";
      break;
      case "quechua":  languajeName = "qu";
      break;
      case "romanche":  languajeName = "rm";
      break;
      case "kirundi":  languajeName = "rn";
      break;
      case "rumano":  languajeName = "ro";
      break;
      case "ruso":  languajeName = "ru";
      break;
      case "ruandés":  languajeName = "rw";
      break;
      case "ruandes":  languajeName = "rw";
      break;
      case "sánscrito":  languajeName = "sa";
      break;
      case "sanscrito":  languajeName = "sa";
      break;
      case "sardo":  languajeName = "sc";
      break;
      case "sindhi":  languajeName = "sd";
      break;
      case "sami septentrional":  languajeName = "se";
      break;
      case "sango":  languajeName = "sg";
      break;
      case "cingalés":  languajeName = "si";
      break;
      case "cingales":  languajeName = "si";
      break;
      case "eslovaco":  languajeName = "sk";
      break;
      case "esloveno":  languajeName = "sl";
      break;
      case "samoano":  languajeName = "sm";
      break;
      case "shona":  languajeName = "sn";
      break;
      case "somalí":  languajeName = "so";
      break;
      case "somali":  languajeName = "so";
      break;
      case "albanés":  languajeName = "sq";
      break;
      case "albanes":  languajeName = "sq";
      break;
      case "serbio":  languajeName = "sr";
      break;
      case "suazi":  languajeName = "ss";
      break;
      case "sesotho":  languajeName = "st";
      break;
      case "sundanés":  languajeName = "su";
      break;
      case "sundanes":  languajeName = "su";
      break;
      case "sueco":  languajeName = "sv";
      break;
      case "suajili":  languajeName = "sw";
      break;
      case "tamil":  languajeName = "ta";
      break;
      case "télugu":  languajeName = "te";
      break;
      case "telugu":  languajeName = "te";
      break;
      case "tayiko":  languajeName = "tg";
      break;
      case "tailandés":  languajeName = "th";
      break;
      case "tailandes":  languajeName = "th";
      break;
      case "tigriña":  languajeName = "ti";
      break;
      case "turcomano":  languajeName = "tk";
      break;
      case "tagalo":  languajeName = "tl";
      break;
      case "setsuana":  languajeName = "tn";
      break;
      case "tongano":  languajeName = "to";
      break;
      case "turco":  languajeName = "tr";
      break;
      case "tsonga":  languajeName = "ts";
      break;
      case "tártaro":  languajeName = "tt";
      break;
      case "tartaro":  languajeName = "tt";
      break;
      case "twi":  languajeName = "tw";
      break;
      case "tahitiano":  languajeName = "ty";
      break;
      case "uigur":  languajeName = "ug";
      break;
      case "ucraniano":  languajeName = "uk";
      break;
      case "urdu":  languajeName = "ur";
      break;
      case "uzbeko":  languajeName = "uz";
      break;
      case "venda":  languajeName = "ve";
      break;
      case "vietnamita":  languajeName = "vi";
      break;
      case "volapük":  languajeName = "vo";
      break;
      case "valón":  languajeName = "wa";
      break;
      case "wolof":  languajeName = "wo";
      break;
      case "xhosa":  languajeName = "xh";
      break;
      case "yídish ":  languajeName = "yi";
      break;
      case "yoruba":  languajeName = "yo";
      break;
      case "chuan":  languajeName = "za";
      break;
      case "chino":  languajeName = "zh";
      break;
      case "zulú":  languajeName = "zu";
      break;
      case "zulu":  languajeName = "zu";
      break;
    }

    //this.languageUrl = `https://restcountries.eu/rest/v2/lang/${ languajeName }`;
    this.languageUrl = `https://restcountries.com/v3.1/lang/${ languajeName }`;
    return this.http.get<CountryResponse>(this.languageUrl);
  }
}
